"""GDELT FIPS 10-4 → ISO 3166-1 alpha-2 변환 테이블"""

FIPS_TO_ISO = {
    "AA": "AW", "AC": "AG", "AE": "AE", "AF": "AF", "AG": "DZ",
    "AJ": "AZ", "AL": "AL", "AM": "AM", "AN": "AD", "AO": "AO",
    "AQ": "AS", "AR": "AR", "AS": "AU", "AU": "AT", "AV": "AI",
    "AY": "AQ", "BA": "BH", "BB": "BB", "BC": "BW", "BD": "BM",
    "BE": "BE", "BF": "BS", "BG": "BD", "BH": "BZ", "BK": "BA",
    "BL": "BO", "BM": "MM", "BN": "BJ", "BO": "BY", "BP": "SB",
    "BR": "BR", "BT": "BT", "BU": "BG", "BV": "BV", "BX": "BN",
    "BY": "BI", "CA": "CA", "CB": "KH", "CD": "TD", "CE": "LK",
    "CF": "CG", "CG": "CD", "CH": "CN", "CI": "CL", "CJ": "KY",
    "CK": "CC", "CM": "CM", "CN": "KM", "CO": "CO", "CQ": "MP",
    "CS": "CR", "CT": "CF", "CU": "CU", "CV": "CV", "CW": "CK",
    "CY": "CY", "DA": "DK", "DJ": "DJ", "DO": "DM", "DR": "DO",
    "EC": "EC", "EG": "EG", "EI": "IE", "EK": "GQ", "EN": "EE",
    "ER": "ER", "ES": "SV", "ET": "ET", "EZ": "CZ", "FG": "GF",
    "FI": "FI", "FJ": "FJ", "FK": "FK", "FM": "FM", "FO": "FO",
    "FP": "PF", "FR": "FR", "FS": "TF", "GA": "GM", "GB": "GA",
    "GG": "GE", "GH": "GH", "GI": "GI", "GJ": "GD", "GK": "GB",
    "GL": "GL", "GM": "DE", "GP": "GP", "GQ": "GU", "GR": "GR",
    "GT": "GT", "GV": "GN", "GY": "GY", "GZ": "PS", "HA": "HT",
    "HK": "HK", "HM": "HM", "HO": "HN", "HU": "HU", "IC": "IS",
    "ID": "ID", "IN": "IN", "IO": "IO", "IR": "IR", "IS": "IL",
    "IT": "IT", "IV": "CI", "IZ": "IQ", "JA": "JP", "JM": "JM",
    "JN": "SJ", "JO": "JO", "KE": "KE", "KG": "KG", "KN": "KP",
    "KR": "KI", "KS": "KR", "KT": "CX", "KU": "KW", "KV": "XK",
    "KZ": "KZ", "LA": "LA", "LE": "LB", "LG": "LV", "LH": "LT",
    "LI": "LR", "LO": "SK", "LS": "LI", "LT": "LS", "LU": "LU",
    "LY": "LY", "MA": "MG", "MB": "MQ", "MC": "MO", "MD": "MD",
    "MF": "YT", "MG": "MN", "MH": "MS", "MI": "MW", "MJ": "ME",
    "MK": "MK", "ML": "ML", "MN": "MC", "MO": "MA", "MP": "MU",
    "MR": "MR", "MT": "MT", "MU": "OM", "MV": "MV", "MX": "MX",
    "MY": "MY", "MZ": "MZ", "NC": "NC", "NE": "NU", "NF": "NF",
    "NG": "NE", "NH": "VU", "NI": "NG", "NL": "NL", "NN": "SX",
    "NO": "NO", "NP": "NP", "NR": "NR", "NS": "SR", "NU": "NI",
    "NZ": "NZ", "OD": "SS", "PA": "PY", "PC": "PN", "PE": "PE",
    "PK": "PK", "PL": "PL", "PM": "PA", "PO": "PT", "PP": "PG",
    "PS": "PW", "PU": "GW", "QA": "QA", "RE": "RE", "RI": "RS",
    "RM": "MH", "RN": "MF", "RO": "RO", "RP": "PH", "RQ": "PR",
    "RS": "RU", "RW": "RW", "SA": "SA", "SB": "PM", "SC": "KN",
    "SE": "SC", "SF": "ZA", "SG": "SN", "SH": "SH", "SI": "SI",
    "SL": "SL", "SM": "SM", "SN": "SG", "SO": "SO", "SP": "ES",
    "ST": "LC", "SU": "SD", "SV": "SJ", "SW": "SE", "SX": "GS",
    "SY": "SY", "SZ": "CH", "TD": "TT", "TH": "TH", "TI": "TJ",
    "TK": "TC", "TL": "TK", "TN": "TO", "TO": "TG", "TP": "ST",
    "TS": "TN", "TT": "TL", "TU": "TR", "TV": "TV", "TW": "TW",
    "TX": "TM", "TZ": "TZ", "UC": "CW", "UG": "UG", "UK": "GB",
    "UP": "UA", "US": "US", "UV": "BF", "UY": "UY", "UZ": "UZ",
    "VC": "VC", "VE": "VE", "VI": "VG", "VM": "VN", "VQ": "VI",
    "VT": "VA", "WA": "NA", "WE": "PS", "WF": "WF", "WI": "EH",
    "WS": "WS", "WZ": "SZ", "YM": "YE", "ZA": "ZM", "ZI": "ZW",
}


def fips_to_iso(fips_code: str) -> str:
    """FIPS 코드를 ISO로 변환. 매핑 없으면 원본 반환."""
    return FIPS_TO_ISO.get(fips_code.upper(), fips_code)
